# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49aca68f601ea809eabd91eed4a15e2d641e68f67856659d3ebfa8d29b050cca2efdea7f3c44bf6bc8b92bb6429a62f93c71f9b57524fb91b32107175676c722

test:
  secret_key_base: 2686c841a2a97cbb925ecfe77fb07d4e01142b890b386e844022bf258c47df4d4596b0bd9d25d26cd3fc2227dc619deb92b36593a077c50c5b9ac550f28e17dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
